### ISSUE TITLE
Standalone mvupdate not working anymore since V0.6.0

### ISSUE THREAD

**Issue by Milhouse77** [mediathekview/plugin.video.mediathekview#118]
Hi.
Thank you for your great work. This plugin in more than helpful and really completes my KODI setup.
Unfortunately, I have a problem with V 0.6.0+: I used a standalone DB-update task (configured “by the book”) on my Synology Nas. Despite the full DB update took like forever (~2h) it was working.
Since I updates to V0.6.0 of the plugin I get error messages.
Output from Console:

```
admin@nas:/$ cd /volume1/Software/Mediathekview
admin@nas:/volume1/Software/Mediathekview$ python2 ./mvupdate -v mysql -P 3307 --user root --password xxxxxxxx -d mediathekview
Traceback (most recent call last):
  File "./mvupdate", line 36, in <module>
    APP.init()
  File "/volume1/Software/Mediathekview/resources/lib/mvupdate.py", line 527, in init
    self.settings = Settings(self.args)
  File "/volume1/Software/Mediathekview/resources/lib/mvupdate.py", line 41, in __init__
    self.updnative = args.native
AttributeError: 'Namespace' object has no attribute 'native'
admin@nas:/volume1/Software/Mediathekview$
```
Could you please advise me?

Many thanks in advance!

**Comment by tuxpoldo** [comment]
The problem has been fixed thanks to a pull request from @dgln - The fix will be released in the next release. you may replace the affected file [resources/lib/mvupdate.py](https://raw.githubusercontent.com/mediathekview/plugin.video.mediathekview/develop/resources/lib/mvupdate.py) with the fixed version (follow the link)

**Comment by Milhouse77** [comment]
Thank you very much. It works now.
But is the duration of 2h "normal" for an full update on a Synology (Maria DB 10)?

**Comment by tuxpoldo** [comment]
Unfortunately yes. But we are working on additional update strategies and we have some idea on how to improve the Update on MySQL/MariaDB - stay tuned.
