### ISSUE TITLE
Standalone DB Update not working with python 3.12

### ISSUE THREAD

**Issue by arcasys** [mediathekview/plugin.video.mediathekview#241]
With python 3.12 mvupdate3 throws the following  error : 
`AttributeError: module 'ssl' has no attribute 'wrap_socket'`

This seems to be due to a change in python 3.12 which is e.g. explained in
[(https://github.com/eventlet/eventlet/issues/795)]

**Comment by arcasys** [comment]
This is actually a defect in `python3-mysql.connector 8.0.15-4` which is the only version supplied in Ubuntu 24.04.
After much trial and error with apt-get and pip to install connectors which looked promising I dug around in the mysql archives:
Download version 3.8.4.0-1 from [https://downloads.mysql.com/archives/c-python]() and install with
`dpkg -i mysql-connector-python-py3_8.4.0-1ubuntu24.04_amd64.deb`
Be careful. In archives, select version 8.4.0 and Ubuntu Linux 24.04. Then don't confuse with other deb files. The one you want is 1.8MB.
This worked for me like a charm.
Although this workaround does not resolve the issue with `python3-mysql.connector 8.0.15-4` I close this issue as resolved.
